### ISSUE TITLE
Aria2 1.37 is out, please update.

### ISSUE THREAD

**Issue by Hellodogfang** [hosxy/aria2-fast#1]
Aria2 v1.37 is out.  Please update. Thank you in advance.

**Comment by Hellodogfang** [comment]
Glad to see that aria2-fast v1.37 has been released, but no exe file?

**Comment by hosxy** [comment]
> Glad to see that aria2-fast v1.37 has been released, but no exe file?

because https://gmplib.org/ can't access, however 
 aria2 need it to build. I am waiting for upstream to fix this problem

**Comment by hosxy** [comment]
> Glad to see that aria2-fast v1.37 has been released, but no exe file?

Now aria2c-fast_x64.exe have been build successful
